"""Pytest contract suite for ``SourceCodeAIDetector``.

These tests define the expected public contract and behavior of the local-only,
language-agnostic AI source-code detector. They never touch the network.

See the QA prompt:
``com_subjective_architecture_docs/worktwins/01_qa_pytest_contracts_source_code_ai_detector.md``
"""

import os

import pytest

from source_code_ai_detector import SourceCodeAIDetector

FIXTURES_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures")


# --------------------------------------------------------------------------
# Helpers
# --------------------------------------------------------------------------
REQUIRED_KEYS = {
    "ai_likelihood",
    "label",
    "confidence",
    "stopped_early",
    "stopped_by",
    "evidence",
    "detectors",
    "input_type",
    "language",
}


def assert_result_contract(result):
    assert REQUIRED_KEYS.issubset(result.keys())
    assert isinstance(result["ai_likelihood"], float)
    assert 0.0 <= result["ai_likelihood"] <= 1.0
    assert result["label"] in {
        "strong_ai_evidence",
        "likely_ai_assisted",
        "inconclusive",
        "low_ai_evidence",
    }
    assert result["confidence"] in {"high", "medium", "low"}
    assert isinstance(result["stopped_early"], bool)
    assert result["stopped_by"] is None or isinstance(result["stopped_by"], str)
    assert isinstance(result["evidence"], list)
    assert isinstance(result["detectors"], list)
    assert result["input_type"] in {"source", "path"}
    for det in result["detectors"]:
        assert {"id", "confidence", "weight", "terminal", "evidence"}.issubset(det.keys())


def detector_ids(result):
    return [d["id"] for d in result["detectors"]]


def read_fixture(*parts):
    with open(os.path.join(FIXTURES_DIR, *parts), "r", encoding="utf-8") as handle:
        return handle.read()


# --------------------------------------------------------------------------
# 1. Explicit AI provenance is terminal
# --------------------------------------------------------------------------
def test_explicit_ai_provenance_is_terminal():
    source = "# Generated by ChatGPT\ndef add(a, b):\n    return a + b\n"
    result = SourceCodeAIDetector.validate(source)
    assert_result_contract(result)

    assert result["ai_likelihood"] >= 0.90
    assert result["label"] == "strong_ai_evidence"
    assert result["confidence"] == "high"
    assert result["stopped_early"] is True
    assert result["stopped_by"] == "explicit_ai_provenance"
    assert any("Generated by ChatGPT".lower() in e.lower() for e in result["evidence"])
    # Lower-priority detectors are not required to run.
    assert "low_else_ratio" not in detector_ids(result)


# --------------------------------------------------------------------------
# 2. AI chat artifacts are terminal or near-terminal
# --------------------------------------------------------------------------
def test_ai_chat_artifacts_high_evidence():
    source = (
        "# Sure, here is the implementation:\n"
        "def normalize_name(name):\n"
        "    return name.strip().lower()\n"
    )
    result = SourceCodeAIDetector.validate(source)
    assert_result_contract(result)

    assert result["ai_likelihood"] >= 0.85
    assert "ai_chat_artifacts" in detector_ids(result)
    assert any("sure, here is" in e.lower() for e in result["evidence"])


# --------------------------------------------------------------------------
# 3. Markdown code fences in source are strong evidence
# --------------------------------------------------------------------------
def test_markdown_code_fence_remnants():
    source = "```python\ndef run():\n    return True\n```\n"
    result = SourceCodeAIDetector.validate(source)
    assert_result_contract(result)

    assert result["ai_likelihood"] >= 0.75
    assert "markdown_code_fence_remnants" in detector_ids(result)
    assert any(
        "fence" in e.lower() or "markdown" in e.lower() for e in result["evidence"]
    )


# --------------------------------------------------------------------------
# 4. Prompt remnants in source are strong evidence
# --------------------------------------------------------------------------
def test_prompt_instruction_remnants():
    source = (
        "# Implement the following function and return only the code.\n"
        "def calculate_total(items):\n"
        "    return sum(items)\n"
    )
    result = SourceCodeAIDetector.validate(source)
    assert_result_contract(result)

    assert "prompt_instruction_remnants" in detector_ids(result)
    assert result["ai_likelihood"] >= 0.70
    assert result["label"] != "low_ai_evidence"


# --------------------------------------------------------------------------
# 5. Placeholder values are medium evidence, not terminal alone
# --------------------------------------------------------------------------
def test_placeholder_values_medium_not_terminal():
    source = 'API_KEY = "your-api-key"\nBASE_URL = "https://example.com"\n'
    result = SourceCodeAIDetector.validate(source)
    assert_result_contract(result)

    assert "placeholder_values" in detector_ids(result)
    assert result["stopped_early"] is False
    assert 0.35 <= result["ai_likelihood"] < 0.90


# --------------------------------------------------------------------------
# 6. Tutorial comments are weak/medium evidence only
# --------------------------------------------------------------------------
def test_tutorial_comments_weak():
    source = (
        "# Loop through the array\n"
        "for x in arr:\n"
        "    process(x)\n"
        "# Return the result\n"
        "return total\n"
    )
    result = SourceCodeAIDetector.validate(source)
    assert_result_contract(result)

    assert "tutorial_comments" in detector_ids(result)
    assert result["ai_likelihood"] < 0.75
    assert result["stopped_early"] is False


# --------------------------------------------------------------------------
# 7. Low else ratio is weak and never terminal
# --------------------------------------------------------------------------
def test_low_else_ratio_weak_never_terminal():
    source = (
        "def classify(n):\n"
        "    if n == 0:\n"
        "        return 'zero'\n"
        "    if n == 1:\n"
        "        return 'one'\n"
        "    if n == 2:\n"
        "        return 'two'\n"
        "    if n < 0:\n"
        "        return 'negative'\n"
        "    return 'many'\n"
    )
    result = SourceCodeAIDetector.validate(source)
    assert_result_contract(result)

    if "low_else_ratio" in detector_ids(result):
        det = next(d for d in result["detectors"] if d["id"] == "low_else_ratio")
        assert det["terminal"] is False
    assert result["ai_likelihood"] <= 0.60
    assert result["stopped_early"] is False


# --------------------------------------------------------------------------
# 8. Human GitHub-style fixture should be low evidence
# --------------------------------------------------------------------------
@pytest.mark.parametrize(
    "fixture_name",
    ["quicksort.py", "lru_cache.py"],
)
def test_human_samples_low_evidence(fixture_name):
    source = read_fixture("human_samples", fixture_name)
    result = SourceCodeAIDetector.validate(source)
    assert_result_contract(result)

    assert result["ai_likelihood"] <= 0.45
    assert result["label"] in {"low_ai_evidence", "inconclusive"}
    assert all(det["terminal"] is False for det in result["detectors"])


# --------------------------------------------------------------------------
# 9. Mixed sample accumulates evidence
# --------------------------------------------------------------------------
def test_mixed_sample_accumulates_evidence():
    source = read_fixture("mixed_samples", "contaminated_config.py")
    result = SourceCodeAIDetector.validate(source)
    assert_result_contract(result)

    assert result["ai_likelihood"] >= 0.55
    assert result["stopped_early"] is False
    assert len(detector_ids(result)) >= 2


# --------------------------------------------------------------------------
# 10. Validate accepts a path
# --------------------------------------------------------------------------
def test_validate_accepts_path(tmp_path):
    path = tmp_path / "generated.py"
    path.write_text("# Generated by ChatGPT\ndef add(a, b):\n    return a + b\n")

    result = SourceCodeAIDetector.validate(str(path))
    assert_result_contract(result)

    assert result["input_type"] == "path"
    assert result["ai_likelihood"] >= 0.90


# --------------------------------------------------------------------------
# 11. Validate accepts raw source strings
# --------------------------------------------------------------------------
def test_validate_accepts_source_string():
    result = SourceCodeAIDetector.validate("def f():\n    return 1\n")
    assert_result_contract(result)
    assert result["input_type"] == "source"
    assert REQUIRED_KEYS.issubset(result.keys())


# --------------------------------------------------------------------------
# 12. Missing file path behavior — treated as source, no crash
# --------------------------------------------------------------------------
def test_missing_path_treated_as_source():
    result = SourceCodeAIDetector.validate("src/not_existing_file.py")
    assert_result_contract(result)
    assert result["input_type"] == "source"


# --------------------------------------------------------------------------
# 13. Empty source behavior
# --------------------------------------------------------------------------
def test_empty_source():
    result = SourceCodeAIDetector.validate("")
    assert_result_contract(result)
    assert result["ai_likelihood"] == 0.0
    assert result["label"] == "low_ai_evidence"
    assert result["evidence"] == []


# --------------------------------------------------------------------------
# 14. Binary / unreadable file path behavior
#
# Chosen behavior: return a safe low-evidence result with an explanatory
# evidence note rather than raising.
# --------------------------------------------------------------------------
def test_binary_file_safe_result(tmp_path):
    path = tmp_path / "blob.bin"
    path.write_bytes(b"\x00\x01\x02\xff\xfe\xfd" * 64)

    result = SourceCodeAIDetector.validate(str(path))
    assert_result_contract(result)

    assert result["input_type"] == "path"
    assert result["ai_likelihood"] == 0.0
    assert any("decode" in e.lower() for e in result["evidence"])


# --------------------------------------------------------------------------
# 15. Deterministic output
# --------------------------------------------------------------------------
def test_deterministic_output():
    source = read_fixture("mixed_samples", "contaminated_config.py")
    first = SourceCodeAIDetector.validate(source)
    second = SourceCodeAIDetector.validate(source)

    assert first["ai_likelihood"] == second["ai_likelihood"]
    assert first["label"] == second["label"]
    assert detector_ids(first) == detector_ids(second)
